# Generated by Django 5.0.3 on 2024-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traducao',
            name='target_language',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='traducao',
            name='language',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
