# Generated by Django 5.0.3 on 2024-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_traducao_target_language_alter_traducao_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traducao',
            name='target_language',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
